// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Em dev, prioriza .env.local (padrão do Next) e depois .env.
loadEnv({ path: ".env.local", override: false });
loadEnv({ path: ".env", override: false });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma Migrate/CLI deve usar conexão direta quando disponível.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
